### ISSUE TITLE
What is the aim of the white papers?

### ISSUE THREAD

**Issue by RaoOfPhysics** [alan-turing-institute/asg-community#14]
From discussion at E&S White Paper kick-off on 24 Jan 2022:

- highlight the best ASG research
- show how the different projects hold together as a coherent whole
- collectively convey some key overarching messages in three key areas (CTPs)
- how to share tools and best practices across domains…
    - identify data challenges that are agnostic to the science domain
- inform and influence government/funding agencies
- highlight why the Turing is an ideal place where the research can be done
    - e.g. Living With Machines was developed for humanities and now being used in E&S

**Comment by malvikasharan** [comment]
I am marking this issue as complete as this info exists in the README: https://github.com/alan-turing-institute/asg-community#ai-for-science-and-government-asg-community-and-white-paper-project
