### ISSUE TITLE
RAM presentation: “Research Applications: taking your research out of the lab”

### ISSUE THREAD

**Issue by RaoOfPhysics** [alan-turing-institute/asg-community#25]
RAMs to give a brief overview on the subject, and possibly flag Turing Partnerships.

- Duration: max 10 minutes
- Tentative date/time: 1 March, 16:00 UTC

Pinging @AidaMehonic, @aldenc and @dingaaling.

See also #24

**Comment by AidaMehonic** [comment]
I hope this was a success @RaoOfPhysics! 
And thanks @aldenc and @dingaaling !!

Should we close this Issue? x
