### ISSUE TITLE
Show & Tell Social Lunch 🥘 

### ISSUE THREAD

**Issue by RaoOfPhysics** [alan-turing-institute/asg-community#37]
Draft message for review:

---

If you’re attending the ASG virtual event in on 1 and 2 March, we would like to invite you to join us for a social lunch on **2 March, from 12:15 to 13:15**.

We will use the time to get to know each other through a “show and tell” over lunch.

**Please order yourself a drink/meal/groceries (budget £??)**

- Since we cannot meet and share a meal in person, we hope that you will enjoy a little treat on us.
- We will reimburse up to £?? for you to have a meal to eat with us.
- You are welcome to take this opportunity to order your favourite meal from a local takeaway, or purchase ingredients/groceries to cook at home for this social call.
- We can reimburse only for food or drink (no hard liquor/alcohol). Please check with Achintya (@RaoOfPhysics or <arao@turing.ac.uk>) or Harriet (@hmccann132 or <hmccann@turing.ac.uk>) if you have any questions.
- To claim your reimbursements for the meal, please see [LINK GOES HERE: see TODO below].

**Show and tell activity (optional but highly encouraged!)**

- Bring along something that you can show and tell others about a favourite hobby, side project or work project.
- We will informally go around the room and have a chance to hear from you, exchange thoughts and ideas beyond our core ASG work.
- You are not required to speak. We will leave the topic entirely up to you to decide. We look forward to learning with you.

---

- [ ] Instructions for reimbursement for Turing and non-Turing people

**Comment by hmccann132** [comment]
Turing policy offers £10 lunch cost as recommended so go with this for budget.

**Comment by hmccann132** [comment]
We need to think through where this info is being shared. Probably best through the Hopin page but then I recommend it be trimmed down a bit (i can help with this). If it were standalone comms it would make sense to be longer. Separately, could think about end of Day 1 comms to summarise Day 1 and keep the interest for day 2
