### ISSUE TITLE
[WIP] Community event status: July 2022

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/asg-community#59]
[Updated by @RaoOfPhysics]

**We are hosting an ASG community event on 7 and 8 July 2022.**

This issue is for the event organisers.

We have created the following checklists, which are chronologically structured to help organise the event in person and online.

**Comment by RaoOfPhysics** [comment]
(Note to self: Refer to this https://github.com/alan-turing-institute/the-turing-way/issues/2301/)
