### ISSUE TITLE
Describe what the demos/workshops are meant to be

### ISSUE THREAD

**Issue by RaoOfPhysics** [alan-turing-institute/asg-community#67]
- **Background**: We have two windows (one hour each) for researcher-led breakout sessions for the in-person attendees on 7 July. The sessions are not meant to be overly formal.
- **Participant numbers**: ~6–8 per table/group
- Type of session:
  - **Discussion**: Are you keen to discuss a burning issue in DS/AI research that you’ve encountered? Propose a topic and gather like-minded researchers to address the issue at hand.
  - **Workshop**: Is there a new technique or package you’ve recently come across? Conduct a workshop on it to share your newly acquired knowledge with your fellow researchers.
  - **Demonstration**: Ready to take your ASG project out into the world? Run a small demonstration to now only show off your work but also get feedback from your fellow attendees.
- Equipment needed: Please contact @ZaynabIsmail and @RaoOfPhysics if you have any special requirements for running your session and we will do our best to accommodate you.

**Comment by RaoOfPhysics** [comment]
Related to #65

**Comment by malvikasharan** [comment]
@AidaMehonic @aldenc @dingaaling do you some guidance from your work in AI-UK that can be reused here. Tagging @ZaynabIsmail who is preparing to share more guidance with the session speakers.

**Comment by ZaynabIsmail** [comment]
Most of the contributors have provided some basic info on what they would like to do.  I would like to make sure we have a fully formed plan and clear directions for the contributors. If you could help with this I would appreciate it. 
The current info is here https://thealanturininstitute.sharepoint.com/:x:/s/rid/Ed2JigIUh09Gv8WvL81na9UBGq9cPBjEHPLetzE6nNjF-g?e=K2Jsp9

**Comment by malvikasharan** [comment]
Dropping a few references here as starting points: 
- General guidance: https://the-turing-way.netlify.app/collaboration/remote-collab/remote-collab-chairs.html
- See RightsCon guide for speakers: https://drive.google.com/drive/folders/19W0GUKHJeyfychuVsHxIphuaaTiNjTlh?usp=sharing

**Comment by malvikasharan** [comment]
Demo:
- Created a generic shared note template that can be adapted for each session and shared with the speaker in advance: https://docs.google.com/document/d/1o-5b_DJiA03Kuk-gitm0Dzw2_4sjg9RI926J4KTil_U/edit?usp=sharing

**Comment by dingaaling** [comment]
Here is the shared note document format that the RAM team used for AI UK! Very similar to the ^ one @malvikasharan shared above - https://docs.google.com/document/d/1D_xc4zLNbi7lwfbUPCLO82Wp0eLbJOY5BVkm-x2JmOM/edit?usp=sharing

We copied questions from the online chat into the notes during the presentation too so the speakers could refer back to them later.

**Comment by ZaynabIsmail** [comment]
The sessions are to be spread across the last two sessions at 2pm and 3:30pm which last for an hour.

**Comment by ZaynabIsmail** [comment]
@dingaaling thank you for the document.

I have created an edited version with questions for you.  Would you be able to have a look when you are available?  A quick huddle call may be quicker. https://thealanturininstitute.sharepoint.com/:w:/s/rid/ER5Dw8JXSjxBozoqxy4-TOMBoui5PS0PX6W7WLo1xNRDZw?e=x6IcPa

**Comment by malvikasharan** [comment]
Looks good @ZaynabIsmail. Make sure to let people know that they can make a copy of your document and remove other session to use it to gather notes from their session.
